name: Build tackle2-hub and kantra images to update seed and rules

on:
  push:
    branches:
      - main
      - 'release-*'

jobs:
  trigger-hub-and-kantra-image-build:
    if: github.repository == 'konveyor/tackle2-seed'
    runs-on: ubuntu-latest
    steps:
      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v4
        with:
          application_id: ${{ vars.KONVEYOR_BOT_ID }}
          application_private_key: ${{ secrets.KONVEYOR_BOT_KEY }}
          revoke_token: 'true'
          permissions: "actions:write"

      - name: Trigger tackle2-hub image build
        env:
          GH_TOKEN: ${{ steps.get_workflow_token.outputs.token }}
          REF_NAME: ${{ github.ref_name }}
        run: |
          gh workflow run march-image-build-push.yml \
            --repo konveyor/tackle2-hub \
            --ref "$REF_NAME"

      - name: Trigger kantra image build
        env:
          GH_TOKEN: ${{ steps.get_workflow_token.outputs.token }}
          REF_NAME: ${{ github.ref_name }}
        run: |
          gh workflow run multi-arch-image-build.yaml \
            --repo konveyor/kantra \
            --ref "$REF_NAME"
