name: Global CI

on:
  push:
    branches:
    - main
    - 'release-*'
    tags:
    - 'v*'
  pull_request:
    branches:
    - main
    - 'release-*'

jobs:
  build-hub:
    name: Build tackle2-hub
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        repository: konveyor/tackle2-hub
        ref: ${{ github.event_name == 'push' && github.ref || github.base_ref }}
        path: tackle2-hub

    - uses: actions/checkout@v3
      with:
        path: tackle2-hub/tackle2-seed

    - name: Build hub and save image
      working-directory: tackle2-hub
      env:
        IMG: ttl.sh/konveyor-hub-${{ github.sha }}:4h
      run: |
        podman build --build-arg SEED_ROOT=/opt/app-root/src/tackle2-seed -t $IMG .
        podman push $IMG

  e2e:
    needs: build-hub
    uses: konveyor/ci/.github/workflows/global-ci-bundle.yml@main
    with:
      operator_bundle: quay.io/konveyor/tackle2-operator-bundle:release-0.9
      run_api_tests: false
      run_koncur_hub_tests: true
      koncur_ref: ${{ github.event_name == 'push' && github.ref || github.base_ref }}
      tackle_cr: |
        kind: Tackle
        apiVersion: tackle.konveyor.io/v1alpha1
        metadata:
          name: tackle
        spec:
          image_pull_policy: IfNotPresent
          analyzer_container_requests_cpu: 100m
          provider_java_container_requests_cpu: 100m
          provider_python_container_requests_cpu: 100m
          feature_auth_required: false
          hub_image_fqin: ttl.sh/konveyor-hub-${{ github.sha }}:4h
